version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ../:/project
      - node_modules_volume:/project/node_modules
    ports:
      - "3000:3000"
    tty: true

volumes:
  node_modules_volume:
